# Generated by Django 3.1.7 on 2021-03-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='DEfault description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='default-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('N', 'primary'), ('S', 'secondary')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Default-title', max_length=100),
            preserve_default=False,
        ),
    ]
