# Generated by Django 3.1.7 on 2021-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210317_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Sale')], max_length=1),
        ),
    ]
